### ISSUE TITLE
Support for ECC in addition with RSA.

### ISSUE THREAD

**Issue by amrx101** [tekjar/rumqtt#75]
ECC is less compute intensive which helps in constrained devices.

https://www.leaderssl.com/articles/345-what-is-ecc-and-why-you-should-use-it

**Comment by amrx101** [comment]
https://github.com/tekjar/rumq/pull/74

**Comment by tekjar** [comment]
Hey. Thanks for this :). I'll review and merge this on Tuesday

**Comment by amrx101** [comment]
Cool, take your time.

**Comment by amrx101** [comment]
@tekjar , should we close this?
